SELECT * FROM hr.employees;

SELECT MAX(SALARY) FROM hr.employees;

SELECT MAX(SALARY) - MIN(SALARY) AS diferenca_salario FROM hr.employees;

SELECT JOB_ID, AVG(SALARY) AS media_salarial
FROM hr.employees
GROUP BY JOB_ID
ORDER BY media_salarial DESC;

SELECT SUM(SALARY) FROM hr.employees;

SELECT ROUND(MAX(SALARY), 2), ROUND(MIN(SALARY), 2), ROUND(SUM(SALARY), 2), ROUND(AVG(SALARY), 2)
FROM hr.employees;

SELECT COUNT(*) FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY)
FROM hr.employees
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY)
FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, ROUND(AVG(SALARY), 2)
FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID <> 'IT_PROG';

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 2), COUNT(*)
FROM hr.employees
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 10;

SELECT PHONE_NUMBER, REPLACE(PHONE_NUMBER, '515', '777') FROM hr.employees;

SELECT * FROM hr.employees
WHERE CHAR_LENGTH(FIRST_NAME) >= 8;

SELECT  EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;

SELECT  EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;

SELECT  EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;

SELECT LAST_NAME, HIRE_DATE FROM hr.employees
WHERE HIRE_DATE BETWEEN '1987-07-01' AND '1987-07-31';

SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) FROM hr.employees;